---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    author: sharmila
    app: voting-project
spec:
  type: ClusterIP
  ports:
    - targetPort: 5432
      port: 5432
  selector:
    author: sharmila
    app: voting-project