---
apiVersion: v1
kind: Pod
metadata:
  name: redis-pod
  labels:
    author: sharmila
    app: voting-project
spec:
  containers:
    - name: redis-pod
      image: redis
      ports:
        - containerPort: 6379
...

