---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  labels:
    author: sharmila
    app: voting-project
spec:
  type: ClusterIP
  ports:
    - targetPort: 6379
      port: 6379
  selector:
    author: sharmila
    app: voting-project