---
apiVersion: v1
kind: Pod
metadata:
  name: result-pod
  labels:
    author: sharmila
    app: voting-project
spec:
  containers:
    - name: result-pod
      image:  dockersamples/examplevotingapp_result
      ports:
        - containerPort: 80
...

