---
apiVersion: v1
kind: Service
metadata:
  name: result-service
  labels:
    author: sharmila
    app: voting-project
spec:
  type: LoadBalancer
  ports:
    - targetPort: 80
      port: 80
  selector:
    author: sharmila
    app: voting-project