---
apiVersion: v1
kind: Pod
metadata:
  name: voting-pod
  labels:
    author: sharmila
    app: voting-project
spec:
    containers:
      - name: voting-pod
        image: dockersamples/examplevotingapp_vote
        ports:
          - containerPort: 80
...





