---
apiVersion: v1
kind: Pod
metadata:
  name: worker-pod
  labels:
    author: sharmila
    app: voting-project
spec:
  containers:
    - name: worker-pod
      image: dockersamples/examplevotingapp_worker
...

